### PR TITLE
re-added cubemapping to default shader

### PR DESCRIPTION
**Pull request by nickdelgrosso**
Cubemapping still seems to work, even with the older shader.

### CODE REVIEW

**Comment by nickdelgrosso** [comment]
@alTeska @mohammadbashiri Could you please test this on your laptops to see if tutorial 4 works with this pull request?

**Comment by alTeska** [comment]
On mine, I get the same error with tutorial 1, 2 and 4:
Error:
> (ratcave) ateska@ateska-XPS-13-9350:~/Desktop/ratcave$ python examples/tutorial4.py 
Traceback (most recent call last):
  File "examples/tutorial4.py", line 58, in <module>
    pyglet.app.run()
  File "/home/ateska/anaconda3/lib/python3.6/site-packages/pyglet/app/__init__.py", line 138, in run
    event_loop.run()
  File "/home/ateska/anaconda3/lib/python3.6/site-packages/pyglet/app/base.py", line 142, in run
    self._run()
  File "/home/ateska/anaconda3/lib/python3.6/site-packages/pyglet/app/base.py", line 154, in _run
    timeout = self.idle()
  File "/home/ateska/anaconda3/lib/python3.6/site-packages/pyglet/app/base.py", line 281, in idle
    window.dispatch_event('on_draw')
  File "/home/ateska/anaconda3/lib/python3.6/site-packages/pyglet/window/__init__.py", line 1232, in dispatch_event
    if EventDispatcher.dispatch_event(self, *args) != False:
  File "/home/ateska/anaconda3/lib/python3.6/site-packages/pyglet/event.py", line 357, in dispatch_event
    if handler(*args):
  File "examples/tutorial4.py", line 54, in on_draw
    virtual_scene.draw360_to_texture(fbo.texture)
  File "/home/ateska/Desktop/ratcave/ratcave/scene.py", line 75, in draw360_to_texture
    self.draw(**kwargs)
  File "/home/ateska/Desktop/ratcave/ratcave/scene.py", line 38, in draw
    mesh.draw()
  File "/home/ateska/Desktop/ratcave/ratcave/mesh.py", line 201, in draw
    vao.draw(mode=self.drawmode)
  File "/home/ateska/Desktop/ratcave/ratcave/vertex.py", line 67, in draw
    self.drawfun(mode)
  File "/home/ateska/Desktop/ratcave/ratcave/vertex.py", line 52, in _draw_elements
    gl.GL_UNSIGNED_INT, 0)
  File "/home/ateska/anaconda3/lib/python3.6/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'

**Comment by nickdelgrosso** [comment]
Okay, I've been able to duplicate the error.  Thanks, @alTeska! It's a strange one--only the shader changed, but now the 'draw_elements' doesn't work?  Looking into it...

**Comment by nickdelgrosso** [comment]
Okay, I can't find the source of the problem--this is more complex than just changing the shader.  Closing pull request and created Issue https://github.com/ratcave/ratcave/issues/36  for further discussion.

**Pull request closed without merging**
