### PR TITLE
Model Matrix Transform

### PR DESCRIPTION
**Pull request by alTeska**
model_matrix_transform added to PhysicalGraph, now it's being calculated in each iteration, which allows position relative to global or parent coordinates. 
Modify option was added to add_child. (child_update function is no longer needed).
PhysicalGraph tests added.

Still needs error testing after changes.

### CODE REVIEW

**Comment by nickdelgrosso** [comment]
Hi Alex,

Travis is showing that the tests aren't passing for this pull request (looks like a problem with the matrix inversion step).  This is a good catch by Travis--but could you please fix this so inversions work without fail and remove the print statements from the tests?

**Comment by alTeska** [comment]
I fixed the error in tests. Also checked the numerical accuracy for the latest version of the code, we are stuck at 1e-4.

**Comment by nickdelgrosso** [comment]
Hi Alex,

Way to find the bug!  However, the change you submitted (removal of scale=0 from tests) does not actually fix the bug, it just doesn't test the value that failed.  This is the kind of thing that will appear later down the road with the same hard-to-diagnose error message.  To solve this, could you please add something  that either raises a ValueError if scale parameters are set to 0 or fixes the matrix upon inversion, thereby avoiding any problems in those situations?

**Comment by alTeska** [comment]
I added the ValueError in __init__ and setter function. Adequate tests are there as well. It does not seem though like the nicest way to do it...

Nevertheless, I think this is a better option than trying to manipulate the matrix operations when one of the diagonals is equal to 0? We do only a single check when the value is being set, don't have to worry about it in each iteration.

**Comment by nickdelgrosso** [comment]
Thanks, looks great!

**Pull request merged**
