### PR TITLE
Cameragroup

### PR DESCRIPTION
**Pull request by mohammadbashiri**
Added the CameraGroup class, with some tests. One thing to note is the test for the look_at methods of the child cameras of a CameraGroup instance. it works only for a special case of point coordinate (x=0, y=0, z=-1).

### CODE REVIEW

**Comment by nickdelgrosso** [comment]
@mohammadbashiri The tests are failing for Python 2.7 and 3.4.  Looks like it's because of the @ symbol used for the dot product.  Could you pleace change this to the numpy.dot() function or method?

**Review by nickdelgrosso — CHANGES_REQUESTED** [review]
Files in the .egg directory shouldn't be added to the repo . 
It looks like the .gitignore file missed it. Could you please remove these files from the pull request?

**Comment by mohammadbashiri** [comment]
Sorry, i did not see the message about the .egg file. I will change that too.

**Review by nickdelgrosso — APPROVED** [review]

**Comment by nickdelgrosso** [comment]
The single-case test for CameraGroup.look_at() worries me.  I've added a test for Physical.look_at() to provide extra security for this method.  @mohammadbashiri could you review and merge this Pull request: https://github.com/mohammadbashiri/ratcave/pull/1  Then we'll have more stability

**Comment by nickdelgrosso** [comment]
Great! Merging.

**Pull request merged**
